/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-12-21 04:12:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class page2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1703131900247L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1703131949924L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>xx飯店</title>\r\n");
      out.write("		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./css/main_color.css\">\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js\"></script>\r\n");
      out.write("		<link rel=\"icon\" type=image/png href=\"images/logopng.png\">\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	.logo-img{\r\n");
      out.write("	 width: 50px; \r\n");
      out.write("	 height: auto;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg bg_main4 fixed-top\">\r\n");
      out.write("			<div class=\"container-fluid\" style=\"margin: 0 20%\">\r\n");
      out.write("			<button class=\"navbar-brand text-light me-0\" onclick=\"window.location.href='./index.jsp'\" style=\"background: none; border: none; padding: 0; cursor: pointer;\">\r\n");
      out.write("        <img src=\"images/logo7.jpg\" alt=\"XX飯店圖片\" class=\"logo-img\">\r\n");
      out.write("    </button>\r\n");
      out.write("   \r\n");
      out.write("				\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("							<a class=\"nav-link text-light ms-5\" href=\"./page1.jsp\">關於我們</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("							<a class=\"nav-link text-light\" href=\"./page2.jsp\">最新消息</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("							<a class=\"nav-link text-light\" href=\"./page3.jsp\">客房介紹</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("							<a class=\"nav-link text-light\" href=\"./page4.jsp\">交通資訊</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person-circle h5 text-light ml-3 mb-0\" role=\"button\" onclick=\"window.location.href='./login.jsp'\">登入</i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./css/main_color.css\">\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js\"></script>\r\n");
      out.write("	<style>\r\n");
      out.write("        /* CSS 樣式 */\r\n");
      out.write("      	.custom-button {\r\n");
      out.write("		  border: 1px solid #000; /* 設置邊框 */\r\n");
      out.write("		  padding: 20px; /* 設置內邊距 */\r\n");
      out.write("		  cursor: pointer; /* 讓滑鼠指針顯示為手形 */\r\n");
      out.write("		  	border-left: none;\r\n");
      out.write("    		border-right: none;\r\n");
      out.write("    		border-top: none;\r\n");
      out.write("    		border-bottom: 1px solid #ccc; /* 只保留底部框線 */\r\n");
      out.write("    		padding: 8px;\r\n");
      out.write("    		text-align: center; /* 靠左對齊 */\r\n");
      out.write("    		background-color: #f2f2f2;\r\n");
      out.write("    		margin: 0 20%; /* 調整左右間距 */\r\n");
      out.write("		}\r\n");
      out.write("		.custom-button:hover {\r\n");
      out.write("		  background-color: #f0f0f0; /* 滑鼠懸停時的背景色 */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.custom-button p:nth-child(1) {\r\n");
      out.write("		  text-align: left; /* 將第一個 <p> 元素文字設為靠左 */\r\n");
      out.write("		}\r\n");
      out.write("		.custom-button p:nth-child(2) {\r\n");
      out.write("		  font-size: 90%; /* 或者你想要的其他比例或像素大小 */\r\n");
      out.write("		  text-align:center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body class=\"bg_main0 vh-100\">\r\n");
      out.write("		<h2 style=\"margin: 0 20%\">最新消息</h2>\r\n");
      out.write("		<section class=\"news-list\" style=\"margin-top: 20px;\">\r\n");
      out.write("		<div class=\"custom-button\" onclick=\"window.location.href='https://gnn.gamer.com.tw/detail.php?sn=260917'\">\r\n");
      out.write("	  <p>日期：2024年1月21日<br>\r\n");
      out.write("	  「富貴圓龍，好運龍來」圓山三大亞太金獎主廚聯手龍年鉅獻,親製無化學添加限量年菜</p>\r\n");
      out.write("	  <p>即日起早鳥9折,加贈圓山限定「好運龍」時尚保冷袋和圓山調味珍鮮</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"custom-button\" onclick=\"window.location.href='https://gnn.gamer.com.tw/detail.php?sn=260917'\">\r\n");
      out.write("	  <p>日期：2023年12月31日<br>\r\n");
      out.write("	  「跨年表演•音樂派對」 DJ現場音樂表演，為您帶來熱情洋溢的跨年夜，盡情舞動身心。</p>\r\n");
      out.write("	  <p> 在夜空中盡情綻放的煙火秀，為新年的來臨增添絢麗色彩，打造夢幻般的跨年時刻。</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"custom-button\" onclick=\"window.location.href='https://gnn.gamer.com.tw/detail.php?sn=260987'\">\r\n");
      out.write("	  <p>日期：2023年12月25日<br>\r\n");
      out.write("	  「星光璀璨•聖誕豪華之旅」,聖誕主題自助晚宴等待您與家人來參與</p>\r\n");
      out.write("	  <p>品嚐來自世界各地的美食佳餚，精選的聖誕甜點，為您帶來美味的節日盛宴。</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"custom-button\" onclick=\"window.location.href='https://gnn.gamer.com.tw/detail.php?sn=260917'\">\r\n");
      out.write("	  <p>日期：2023年12月22日<br>\r\n");
      out.write("	  「冬至搓湯圓•手作湯圓體驗」,與親子一起體驗搓湯圓的樂趣！製作屬於自己的湯圓。</p>\r\n");
      out.write("	  <p>每位小朋友完成湯圓製作後，將獲得一份小禮物，感謝他們的參與和創意。</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"custom-button\" onclick=\"window.location.href='https://gnn.gamer.com.tw/detail.php?sn=260917'\">\r\n");
      out.write("	  <p>日期：2023年11月20日<br>\r\n");
      out.write("	  「鍛鍊金工•手作體驗」使用鍛打、雕刻等技法，親手製作個性化的金屬飾品，打造獨特風格。</p>\r\n");
      out.write("	  <p>即日起兩人同行一人半價,歡迎情侶同遊。</p>\r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("	<div class=\"custom-button\" onclick=\"window.location.href='https://gnn.gamer.com.tw/detail.php?sn=260917'\">\r\n");
      out.write("	  <p>日期：2023年11月07日<br>\r\n");
      out.write("	  「螃蟹產季•饗您味蕾」提供多種獨特口味的螃蟹料理，從清蒸、紅燒到香辣，滿足不同口味的需求。</p>\r\n");
      out.write("	  <p>即日起早鳥9折,消費滿兩千折兩百。</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("  /* 在這裡新增導覽列的背景色 */\r\n");
      out.write("  .fotter-bg-color {\r\n");
      out.write("    background-color: #B0A695;\r\n");
      out.write("     border: 1px solid transparent; /* 設定導覽列的邊框 */\r\n");
      out.write("    border-radius: 0; /* 可能需要將邊框的圓角設定為 0，視情況而定 */\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("<footer class=\"position-fixed bottom-0  fotter-bg-color w-100 text-light text-center fixed-bottom\">\r\n");
      out.write("  <p class=\"mb-0\">&copy; 2023 飯店管理網站. 聯絡地址: . 聯絡電話:.</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <div style=\"height: 5vh;\"></div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
